interface AgentSection {
  label: string;
  text: string;
}

/**
 * Merges independent agent responses into one structured markdown document.
 * Kept intentionally simple/deterministic (no extra LLM call) — headings are
 * organized, duplicate section titles are stripped from agent output, and a
 * consistent document shape is produced every time.
 */
export function aggregateToMarkdown(topic: string, sections: AgentSection[]): string {
  const body = sections
    .map((s) => `## ${s.label}\n\n${stripLeadingHeading(s.text).trim()}`)
    .join("\n\n---\n\n");

  return `# ${toTitleCase(topic)}\n\n${body}\n\n---\n\n## References\n\n_Generated by Brain Freeze multi-agent research pipeline._\n`;
}

function stripLeadingHeading(text: string): string {
  return text.replace(/^#{1,3}\s.*\n+/, "");
}

function toTitleCase(topic: string): string {
  return topic
    .split(" ")
    .map((w) => (w.length ? w[0].toUpperCase() + w.slice(1) : w))
    .join(" ");
}